spring:
  application:
    name: myspringboot #eureka服务端起个名字
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/mysqltotest?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

    initiaSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECE 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    filters: stat,wall,log4j
    maxPoolPrepareStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapperLocations: classpath:mapping/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.yuhaisheng.github.entity

server:
  port: 8763 #修改端口号

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

